//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtigosClientes
    {
        public string Cliente { get; set; }
        public string Artigo { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<decimal> Preco1 { get; set; }
        public Nullable<decimal> Preco2 { get; set; }
        public Nullable<decimal> Preco3 { get; set; }
    }
}
