//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artigo()
        {
            this.ArtigosClientes = new HashSet<ArtigosClientes>();
            this.ComponentesDosArtigos = new HashSet<ComponentesDosArtigos>();
            this.Encomenda = new HashSet<Encomenda>();
            this.Feitas = new HashSet<Feitas>();
            this.VerPrecos = new HashSet<VerPrecos>();
        }
    
        public string Nome { get; set; }
        public int ID { get; set; }
        public string UnBase { get; set; }
        public Nullable<int> QtdCartao { get; set; }
        public Nullable<int> QtdCartolina { get; set; }
        public Nullable<int> QtdCartoesPalete { get; set; }
        public string Cartao { get; set; }
        public string Cartolina { get; set; }
        public string Maquina1 { get; set; }
        public string Maquina2 { get; set; }
        public string Maquina3 { get; set; }
        public string Maquina4 { get; set; }
        public string Maquina5 { get; set; }
    
        public virtual Cartao Cartao1 { get; set; }
        public virtual Cartolina Cartolina1 { get; set; }
        public virtual Maquina Maquina { get; set; }
        public virtual Maquina Maquina6 { get; set; }
        public virtual Maquina Maquina7 { get; set; }
        public virtual Maquina Maquina8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtigosClientes> ArtigosClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentesDosArtigos> ComponentesDosArtigos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda> Encomenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feitas> Feitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerPrecos> VerPrecos { get; set; }
    }
}
