//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigo
    {
        public string Nome { get; set; }
        public int ID { get; set; }
        public string UnBase { get; set; }
        public Nullable<int> QtdCartao { get; set; }
        public Nullable<int> QtdCartolina { get; set; }
        public Nullable<int> QtdCartoesPalete { get; set; }
        public string Cartao { get; set; }
        public string Cartolina { get; set; }
        public string Maquina1 { get; set; }
        public string Maquina2 { get; set; }
        public string Maquina3 { get; set; }
        public string Maquina4 { get; set; }
        public string Maquina5 { get; set; }
    }
}
