//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        public string Designacao { get; set; }
        public string PrecoCartolina { get; set; }
        public string Volume { get; set; }
        public string Moeda { get; set; }
    }
}
