//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string ID { get; set; }
        public string Nome { get; set; }
        public string Localidade { get; set; }
        public Nullable<decimal> MargemLucro { get; set; }
        public string Transporte { get; set; }
        public string TipoEsterilizacao { get; set; }
    }
}
