//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.ArtigosClientes = new HashSet<ArtigosClientes>();
            this.Encomenda = new HashSet<Encomenda>();
        }
    
        public string ID { get; set; }
        public string Nome { get; set; }
        public string Localidade { get; set; }
        public Nullable<float> MargemLucro { get; set; }
        public string Transporte { get; set; }
        public string TipoEsterilizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtigosClientes> ArtigosClientes { get; set; }
        public virtual Esterilizacao Esterilizacao { get; set; }
        public virtual Transporte Transporte1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encomenda> Encomenda { get; set; }
        public virtual VerPrecos VerPrecos { get; set; }
    }
}
