//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentesDosArtigos
    {
        public string Artigo { get; set; }
        public string Componente { get; set; }
        public string Quantidade { get; set; }
    
        public virtual Artigo Artigo1 { get; set; }
        public virtual Componentes Componentes { get; set; }
    }
}
