//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componentes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Componentes()
        {
            this.ComponentesDosArtigos = new HashSet<ComponentesDosArtigos>();
            this.Feitas = new HashSet<Feitas>();
        }
    
        public string Nome { get; set; }
        public Nullable<int> ID { get; set; }
        public string Transporte { get; set; }
        public Nullable<float> PrecoCompra { get; set; }
        public string Moeda { get; set; }
        public Nullable<float> PrecoCusto { get; set; }
        public Nullable<float> CustoAlfandega { get; set; }
        public Nullable<int> QtdCartao { get; set; }
        public Nullable<float> VolCartao { get; set; }
        public string UnBase { get; set; }
        public Nullable<float> PrecoCustoFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComponentesDosArtigos> ComponentesDosArtigos { get; set; }
        public virtual Moeda Moeda1 { get; set; }
        public virtual Transporte Transporte1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feitas> Feitas { get; set; }
    }
}
