//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componentes
    {
        public string Nome { get; set; }
        public Nullable<int> ID { get; set; }
        public string Transporte { get; set; }
        public Nullable<decimal> PrecoCompra { get; set; }
        public string Moeda { get; set; }
        public Nullable<decimal> PrecoCusto { get; set; }
        public Nullable<decimal> CustoAlfandega { get; set; }
        public Nullable<int> QtdCartao { get; set; }
        public Nullable<decimal> VolCartao { get; set; }
        public string UnBase { get; set; }
        public Nullable<decimal> PrecoCustoFinal { get; set; }
    }
}
