//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encomenda
    {
        public int NumeroEnco { get; set; }
        public string Artigo { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<System.DateTime> DataLimite { get; set; }
        public Nullable<System.DateTime> DataEntregaPrevista { get; set; }
        public string Estado { get; set; }
    }
}
