//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquina
    {
        public string Nome { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> MinPessFrente { get; set; }
        public Nullable<int> MaxPessFrente { get; set; }
        public Nullable<int> MinPessTras { get; set; }
        public Nullable<int> MaxPessTras { get; set; }
        public string Filme { get; set; }
        public string Papel { get; set; }
        public string Molde { get; set; }
        public string Velocidade1 { get; set; }
        public string Velocidade2 { get; set; }
    }
}
