//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maquina()
        {
            this.Artigo = new HashSet<Artigo>();
            this.Artigo1 = new HashSet<Artigo>();
            this.Artigo2 = new HashSet<Artigo>();
            this.Artigo3 = new HashSet<Artigo>();
        }
    
        public string Nome { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> MinPessFrente { get; set; }
        public Nullable<int> MaxPessFrente { get; set; }
        public string Filme { get; set; }
        public string Papel { get; set; }
        public string Molde { get; set; }
        public string Velocidade1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artigo> Artigo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artigo> Artigo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artigo> Artigo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artigo> Artigo3 { get; set; }
        public virtual Filme Filme1 { get; set; }
        public virtual Molde Molde1 { get; set; }
        public virtual Papel Papel1 { get; set; }
        public virtual TipoMaquina TipoMaquina { get; set; }
        public virtual PessoasMaquinas PessoasMaquinas { get; set; }
    }
}
