//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedirmDBEntities1 : DbContext
    {
        public MedirmDBEntities1()
            : base("name=MedirmDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artigo> Artigo { get; set; }
        public virtual DbSet<Cartao> Cartao { get; set; }
        public virtual DbSet<Cartolina> Cartolina { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Componentes> Componentes { get; set; }
        public virtual DbSet<CustosFixos> CustosFixos { get; set; }
        public virtual DbSet<Encomenda> Encomenda { get; set; }
        public virtual DbSet<Esterilizacao> Esterilizacao { get; set; }
        public virtual DbSet<Ferias> Ferias { get; set; }
        public virtual DbSet<Filme> Filme { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Maquina> Maquina { get; set; }
        public virtual DbSet<Moeda> Moeda { get; set; }
        public virtual DbSet<Molde> Molde { get; set; }
        public virtual DbSet<Papel> Papel { get; set; }
        public virtual DbSet<TipoMaquina> TipoMaquina { get; set; }
        public virtual DbSet<Transporte> Transporte { get; set; }
        public virtual DbSet<TurnosFuncionarios> TurnosFuncionarios { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<ArtigosClientes> ArtigosClientes { get; set; }
        public virtual DbSet<ComponentesDosArtigos> ComponentesDosArtigos { get; set; }
        public virtual DbSet<Feitas> Feitas { get; set; }
        public virtual DbSet<PessoasMaquinas> PessoasMaquinas { get; set; }
        public virtual DbSet<VerPrecos> VerPrecos { get; set; }
    }
}
