//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Molde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Molde()
        {
            this.Maquina = new HashSet<Maquina>();
        }
    
        public string Designacao { get; set; }
        public string Cortantes { get; set; }
        public string PecasPorAvanco { get; set; }
        public Nullable<float> MetrosPorAvanco { get; set; }
        public Nullable<float> Profundidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maquina> Maquina { get; set; }
    }
}
