//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Molde
    {
        public string Designacao { get; set; }
        public string Cortantes { get; set; }
        public string PecasPorAvanco { get; set; }
        public Nullable<decimal> MetrosPorAvanco { get; set; }
        public Nullable<decimal> Profundidade { get; set; }
    }
}
