//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporte
    {
        public string Designacao { get; set; }
        public string Preco { get; set; }
        public string Moeda { get; set; }
        public string Transportadora { get; set; }
        public string Utilizador { get; set; }
        public string De { get; set; }
        public string Para { get; set; }
        public string Info { get; set; }
    }
}
