//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDIRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnosFuncionarios
    {
        public string Funcionario { get; set; }
        public string DiaDaSemana { get; set; }
        public string Turno1 { get; set; }
        public string Turno2 { get; set; }
        public string Turno3 { get; set; }
        public string Turno4 { get; set; }
    }
}
